### ISSUE TITLE
Deployment Size limits not respected for individual agents templates 

### ISSUE THREAD

**Issue by one-random-dev** [jenkinsci/azure-vm-agents-plugin#325] opened 2021-11-09 11:23 UTC
### Version report

Jenkins and plugins versions report:
```
Jenkins: 2.289.2
OS: Linux - 5.4.0-1056-azure
---
azure-vm-agents:797.v31f530348574
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Jenkins hosted on Linux (kubernetes cluster)}
Windows VM AGents
```

### Reproduction steps

- Create a Azure VM Agents Cloud
- Set cloud deployment size limit to 10
- Create a template and set it's deployment size limit to five
- Create a second template and set it's deployment size limit to five 
- launch 10 jobs for each of the agent templates 

### Results

Expected result: 5 vms of each would be spawned to deal with the first five elements of the queue on each of the templates / node labels

Actual result: random outcome, 10 vms can spawn for a single template effectively stopping only at the Cloud Deployment Size limit, not at it's template size limit 

We use this to ensure the certain builds / tags get priority over other builds, based on the node label.
Now those builds just depend on the queue position as the limits are not being respected

**Comment by timja** [comment] 2021-11-09 12:01
Is this something that has changed? Or never worked?

**Comment by one-random-dev** [comment] 2021-11-10 09:38
I know it was working when it was first included, was only noticed now with the latest version although we could have stayed away from the bug conditions previously

**Comment by tchrischan** [comment] 2021-12-02 17:30
Seeing this also, have a template limit of 2 and 10 agents were spawned in the last 24 hours with a bunch of commits. This effectively starved other jobs because we hit the cloud limit rather quickly.

**Comment by timja** [comment] 2021-12-02 19:25
I think this is a duplicate of https://github.com/jenkinsci/azure-vm-agents-plugin/issues/249 ?

Which should be quite straightforward to implement

**Comment by tchrischan** [comment] 2021-12-02 19:31
@timja I think so?
Also want to report back I downgraded to v783.58077630847d and that did not solve the problem. So maybe I just imagined it used to respect the set value.

**Closed** 2021-12-02 19:32 UTC
Labels: bug
