### ISSUE TITLE
Delete agent after build execution: occationaly only removes VM, but keep NIC and disk

### ISSUE THREAD

**Issue by duchenpaul** [jenkinsci/azure-vm-agents-plugin#401] opened 2023-04-13 01:01 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.397
OS: Linux - 5.4.0-1105-azure
Java: 11.0.18 - Ubuntu (OpenJDK 64-Bit Server VM)
---
ace-editor:1.1
ansicolor:1.0.2
ant:481.v7b_09e538fcca
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
artifactory:3.18.0
atlassian-bitbucket-server-integration:3.3.2
audit-trail:333.vb_e1b_b_0f1238c
authentication-tokens:1.4
authorize-project:1.5.1
azure-credentials:254.v64da_8176c83a
azure-sdk:118.v43f74dd9ca_dc
azure-vm-agents:825.v470cb_9e7361a_
basic-branch-build-strategies:71.vc1421f89888e
bitbucket:223.vd12f2bca5430
blueocean:1.27.3
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.3
blueocean-commons:1.27.3
blueocean-config:1.27.3
blueocean-core-js:1.27.3
blueocean-dashboard:1.27.3
blueocean-display-url:2.4.1
blueocean-events:1.27.3
blueocean-git-pipeline:1.27.3
blueocean-github-pipeline:1.27.3
blueocean-i18n:1.27.3
blueocean-jira:1.27.3
blueocean-jwt:1.27.3
blueocean-personalization:1.27.3
blueocean-pipeline-api-impl:1.27.3
blueocean-pipeline-editor:1.27.3
blueocean-pipeline-scm-api:1.27.3
blueocean-rest:1.27.3
blueocean-rest-impl:1.27.3
blueocean-web:1.27.3
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.2-2
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-user-vars-plugin:1.9
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
change-assembly-version-plugin:1.10
checks-api:2.0.0
cloud-stats:267.v577e3742c282
cloudbees-bitbucket-branch-source:800.va_b_b_9a_a_5035c1
cloudbees-folder:6.815.v0dd5a_cb_40e0e
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
config-file-provider:3.11.1
configuration-as-code:1616.v11393eccf675
copyartifact:686.v6fd37018d7c2
credentials:1224.vc23ca_a_9a_2cb_0
credentials-binding:523.vd859a_4b_122e6
custom-tools-plugin:0.8
data-tables-api:1.13.3-3
display-url-api:2.3.7
docker-commons:419.v8e3cd84ef49c
docker-workflow:563.vd5d2e5c4007f
dtkit-api:3.0.2
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-3
email-ext:2.95
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:359.v35dcfdd0c20d
extended-read-permission:3.2
external-monitor-job:203.v683c09d993b_9
favorite:2.4.1
file-operations:1.11
font-awesome-api:6.3.0-2
git:5.0.0
git-client:4.2.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.0
github-api:1.303-417.ve35d9dd78549
github-branch-source:1703.vd5a_2b_29c6cdc
google-oauth-plugin:1.0.8
gradle:2.3.2
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hashicorp-vault-plugin:360.v0a_1c04cf807d
htmlpublisher:1.31
http_request:1.16
instance-identity:142.v04572ca_5b_265
ionicons-api:45.vf54fca_5d2154
ivy:2.4
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.3
jersey2-api:2.39.1-1
jira:3.9
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
job-dsl:1.83
jobConfigHistory:1207.vd28a_54732f92
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.4-1
jsch:0.1.55.61.va_e9ee26616e7
junit:1189.v1b_e593637fa_e
kubernetes:3900.va_dce992317b_4
kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
kubernetes-credentials:0.10.0
ldap:671.v2a_9192a_7419d
lockable-resources:1131.vb_7c3d377e723
mailer:448.v5b_97805e3767
mapdb-api:1.0.9-28.vf251ce40855d
mask-passwords:150.vf80d33113e80
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.21
mercurial:1260.vdfb_723cdcc81
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-62.v199162f0a_2f8
mina-sshd-api-core:2.9.2-62.v199162f0a_2f8
momentjs:1.1.1
msbuild:1.30
next-build-number:1.8
nodejs:1.6.0
nodelabelparameter:1.11.0
nunit:0.28
oauth-credentials:0.5
okhttp-api:4.10.0-132.v7a_7b_91cef39c
pam-auth:1.10
parameterized-scheduler:1.2
pipeline-build-step:487.va_823138eee8b_
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2125.vddb_a_44a_d605e
pipeline-model-definition:2.2125.vddb_a_44a_d605e
pipeline-model-extensions:2.2125.vddb_a_44a_d605e
pipeline-rest-api:2.32
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2125.vddb_a_44a_d605e
pipeline-stage-view:2.32
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.2.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
powershell:2.0
promoted-builds:892.vd6219fc0a_efb
pubsub-light:1.17
resource-disposer:0.21
role-strategy:587.588.v850a_20a_30162
run-condition:1.5
saml:4.385.v4dea_91565e9d
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
slack:631.v40deea_40323b
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sonar:2.15
sse-gateway:1.26
ssh-agent:327.v230ecd01f86f
ssh-credentials:305.v8f4381501156
ssh-slaves:2.877.v365f5eb_a_b_eec
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
subversion:2.17.1
timestamper:1.23
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
uno-choice:2.6.4
urltrigger:1.02
variant:59.vf075fe829ccb
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3653.v07ea_433c90b_4
workflow-durable-task-step:1241.v1a_63e465f943
workflow-job:1289.vd1c337fd5354
workflow-multibranch:733.v109046189126
workflow-scm-step:408.v7d5b_135a_b_d49
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
xtrigger-api:1.0
xunit:3.1.2
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

controller: Debian 11
agent: Windows 

### Reproduction steps

We use azure agents to run builds, and it destroys itself once the build is completed, but we can see some agents hanging in jenkins, it stays there forever.
![image](https://user-images.githubusercontent.com/8120099/231617737-f9ab34e9-e704-424c-814f-3577d522ca6a.png)

By seeing the agent for azure portal, we can see that VM resources (VM, NIC, disk), the VM is gone, and only NIC and disk remain.
![Snipaste_2023-04-13_08-57-18](https://user-images.githubusercontent.com/8120099/231618308-a316dc2b-e2cc-4884-8ee2-b1a0cbef38fc.png)
ng. We expect all 3 resources are purged, then the node to be removed from jenkins.

This happens sometimes, but not always.

### Expected Results

We expect all 3 resources are purged, then the node is removed from jenkins.
Here is the log from a normal agent, we can see it has steps of removing NIC & disk:
```
2023-04-12 09:22:40 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate removeIPName Remove NIC hdx-prod7bf460NIC
2023-04-12 09:22:40 INFO com.microsoft.azure.vmagent.AzureVMAgent deprovision hdx-prod7bf460 has been deprovisioned. Remove node ...
2023-04-12 09:22:40 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate terminateVirtualMachine Clean operation starting for hdx-prod7bf460 NIC and IP
2023-04-12 09:22:10 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate terminateVirtualMachine Removing managed disk with id: /subscriptions/22d01938-666f-47e4-b135-6034e961b532/resourceGroups/ct-prd-cicd-jenkins-hdx-dynamic-rg/providers/Microsoft.Compute/disks/hdx-prod7bf460_disk1_f48ddf739bad4b13a9ce8d481da87d92
2023-04-12 09:21:44 INFO jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed IOHub#1: Worker[channel:java.nio.channels.SocketChannel[connected local=/10.73.56.148:50000 remote=10.73.60.20/10.73.60.20:50167]] / Computer.threadPoolForRemoting [#12121] for hdx-prod7bf460 terminated: java.nio.channels.ClosedChannelException
2023-04-12 09:21:29 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate terminateVirtualMachine Removing virtual machine hdx-prod7bf460
2023-04-12 09:21:29 INFO jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed Computer.threadPoolForRemoting [#12118] for hdx-prod7bf460 terminated: java.nio.channels.ClosedChannelException
2023-04-12 09:21:29 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate virtualMachineExists Checking VM exists for hdx-prod7bf460
2023-04-12 09:21:29 INFO com.microsoft.azure.vmagent.AzureVMAgent deprovision Deprovision called for agent hdx-prod7bf460, for reason: Delete agent after build execution (when idle).
2023-04-12 09:21:29 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate virtualMachineExists Checking VM exists for hdx-prod7bf460
```

### Actual Results

For some agents, we can see that VM resources (VM, NIC, disk), the VM is gone, only NIC and disk remain.
Here is jenkins log, no steps of removing NIC & disk
```
2023-03-14 20:15:17 INFO jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed IOHub#1: Worker[channel:java.nio.channels.SocketChannel[connected local=/10.73.56.148:50000 remote=10.73.60.19/10.73.60.19:53400]] / Computer.threadPoolForRemoting [#11328] for hdx-prodab89c0 terminated: java.nio.channels.ClosedChannelException
2023-03-14 20:15:12 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate terminateVirtualMachine Removing virtual machine hdx-prodab89c0
2023-03-14 20:15:12 INFO jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed Computer.threadPoolForRemoting [#11285] for hdx-prodab89c0 terminated: java.nio.channels.ClosedChannelException
2023-03-14 20:15:12 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate virtualMachineExists Checking VM exists for hdx-prodab89c0
2023-03-14 20:15:12 INFO com.microsoft.azure.vmagent.AzureVMAgent deprovision Deprovision called for agent hdx-prodab89c0, for reason: Delete agent after build execution (when idle).
2023-03-14 20:15:11 INFO com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate virtualMachineExists Checking VM exists for hdx-prodab89c0
```

**Comment by timja** [comment] 2023-04-13 07:28
Duplicate of https://github.com/jenkinsci/azure-vm-agents-plugin/issues/380

But your issue provides some useful information.

In your Expected results log I think you might be showing the end of a previous agent and the beginning of the delete of a next one.

I can't see anything from logs or code that would stop it from at least logging `Clean operation starting for $agentName NIC and IP`

It might be better that we change to using the new-ish feature to delete the NIC and disk on VM termination instead:
https://learn.microsoft.com/en-us/azure/virtual-machines/delete?tabs=rest2%2Ccli3%2Cportal4%2Cportal5#set-delete-options-when-creating-a-vm

**Comment by timja** [comment] 2023-04-20 08:09
I've started work on this in https://github.com/jenkinsci/azure-vm-agents-plugin/pull/405

**Closed** 2023-04-20 09:25 UTC
Labels: bug
