### ISSUE TITLE
Readme doesn't capture permissions needed on Azure Service Prinicipal

### ISSUE THREAD

**Issue by alwaysharsha** [jenkinsci/azure-vm-agents-plugin#403] opened 2023-04-17 06:07 UTC
### Describe your use-case which is not covered by existing documentation.

In the readme.md we just have below information

> To use this plugin to create VM agents, first you need to have an Azure Service Principal in your Jenkins instance.

If we could also specify what specific permissions are needed instead of providing wider access would be helpful to limit the misuse of the permissions.

**Comment by timja** [comment] 2023-04-17 07:27
Contributor, or Virtual Machine Contributor and maybe Network Contributor would be built-in roles that would work.

Please try it out and contribute to the docs for this usecase.

Thanks

**Comment by timja** [comment] 2023-04-30 19:52
Duplicate of https://github.com/jenkinsci/azure-vm-agents-plugin/issues/374

**Closed by timja** 2023-04-30 19:52 UTC
Labels: documentation
